/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SubstackCopyPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var SubstackCopyPlugin = class extends import_obsidian.Plugin {
  async onload() {
    console.log("Loading Substack Copy Plugin");
    this.addCommand({
      id: "copy-for-substack",
      name: "Copy for Substack",
      checkCallback: (checking) => {
        const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
        if (view) {
          if (!checking) {
            this.processMarkdown(view);
          }
          return true;
        }
        return false;
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian.TFile && file.extension === "md") {
          menu.addItem((item) => {
            item.setTitle("Copy for Substack").setIcon("documents").onClick(async () => {
              var _a;
              const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
              if (view && view.file === file) {
                this.processMarkdown(view);
              } else {
                const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
                if (activeView && ((_a = activeView.file) == null ? void 0 : _a.path) === file.path) {
                  this.processMarkdown(activeView);
                } else {
                  new import_obsidian.Notice("Please open the note to copy.");
                }
              }
            });
          });
        }
      })
    );
  }
  async processMarkdown(view) {
    try {
      const editor = view.editor;
      const file = view.file;
      if (!file)
        return;
      let markdown = editor.getSelection();
      if (!markdown) {
        markdown = editor.getValue();
      }
      const container = document.createElement("div");
      await import_obsidian.MarkdownRenderer.render(this.app, markdown, container, file.path, new import_obsidian.Component());
      await this.replaceImagesWithBase64(container, file.path);
      const html = container.innerHTML;
      const plainText = container.innerText;
      if (import_obsidian.Platform.isDesktopApp) {
        const { clipboard } = require("electron");
        clipboard.write({
          text: plainText,
          html
        });
      } else {
        try {
          const data = [new ClipboardItem({
            "text/plain": new Blob([plainText], { type: "text/plain" }),
            "text/html": new Blob([html], { type: "text/html" })
          })];
          await navigator.clipboard.write(data);
        } catch (mobileError) {
          console.error("Mobile Clipboard Error:", mobileError);
          new import_obsidian.Notice("Mobile Copy Error: " + (mobileError.message || mobileError));
          throw mobileError;
        }
      }
      new import_obsidian.Notice("Content copied for Substack!");
    } catch (error) {
      console.error("Substack Copy Error:", error);
      new import_obsidian.Notice("Error copying content. Check console for details: " + (error.message || error));
    }
  }
  async replaceImagesWithBase64(container, sourcePath) {
    var _a;
    const images = container.querySelectorAll("img");
    for (let i = 0; i < images.length; i++) {
      const img = images[i];
      const src = img.getAttribute("src");
      if (!src)
        continue;
      try {
        if (src.startsWith("http://") || src.startsWith("https://")) {
          continue;
        }
        let filenameRaw = (_a = src.split("/").pop()) == null ? void 0 : _a.split("?")[0];
        if (!filenameRaw)
          continue;
        let filename = decodeURIComponent(filenameRaw);
        let file = this.app.metadataCache.getFirstLinkpathDest(filename, sourcePath);
        if (file) {
          const arrayBuffer = await this.app.vault.readBinary(file);
          const base64 = (0, import_obsidian.arrayBufferToBase64)(arrayBuffer);
          const mimeType = this.getMimeType(file.extension);
          img.src = `data:${mimeType};base64,${base64}`;
        }
      } catch (e) {
        console.error(`Failed to process image: ${src}`, e);
      }
    }
  }
  getMimeType(extension) {
    switch (extension.toLowerCase()) {
      case "png":
        return "image/png";
      case "jpg":
      case "jpeg":
        return "image/jpeg";
      case "gif":
        return "image/gif";
      case "webp":
        return "image/webp";
      case "svg":
        return "image/svg+xml";
      default:
        return "application/octet-stream";
    }
  }
};
